services:
  backend:
    build:
     context: .
     dockerfile: Dockerfile
    container_name: booking-fastapi
    # command: tail -F anything
    ports:
      - '8000:8000'
  
networks:
  default:
    name: base-network
    external: true