services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Test1234!"
    ports:
      - 1433:1433
    volumes:
      - mssqlsystem:/var/opt/mssql
      - mssqluser:/var/opt/sqlserver
    networks:
      - default


  nginx:
    image: nginx:latest
    container_name: nginx-booking
    environment:
      DOMAIN: localhost
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    ports:
      - 80:80
    networks:
      - default
    restart: always

networks:
  default:
    name: base-network

volumes:
  mssqlsystem:
  mssqluser: 
